-- MySQL Script generated by MySQL Workbench
-- Wed Jul 22 10:09:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_Laboratorio_ARFE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BD_Laboratorio_ARFE` ;

-- -----------------------------------------------------
-- Schema BD_Laboratorio_ARFE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_Laboratorio_ARFE` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `BD_Laboratorio_ARFE` ;

-- -----------------------------------------------------
-- Table `Categoria_Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categoria_Producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Categoria_Producto` (
  `idCategoriaProducto` INT NOT NULL AUTO_INCREMENT,
  `CategoriaProductoNombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idCategoriaProducto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Facturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Facturacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Facturacion` (
  `NumeroFactura` VARCHAR(11) NOT NULL,
  `FacturacionFecha` DATE NOT NULL,
  `FacturacionTipoPago` INT NOT NULL,
  `FacturacionISV` INT(3) NOT NULL,
  `FacturacionSubTotal` DECIMAL(10,2) NOT NULL,
  `FacturacionTotal` DECIMAL(10,2) NOT NULL,
  `Paciente_idPaciente` INT NOT NULL,
  `TipoExamen_idTipoExamen` INT NOT NULL,
  PRIMARY KEY (`NumeroFactura`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Paciente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `PacienteFecha` DATE NOT NULL,
  `PacienteNombres` VARCHAR(30) NOT NULL,
  `PacienteApellidos` VARCHAR(30) NOT NULL,
  `PacienteIdentidad` VARCHAR(15) NOT NULL,
  `PacienteEdad` INT(2) NOT NULL,
  `PacienteSexo` VARCHAR(10) NOT NULL,
  `PacienteTelefono` VARCHAR(10) NOT NULL,
  `PacienteCorreo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `ProductoNombre` VARCHAR(50) NOT NULL,
  `ProductoDescripcion` VARCHAR(250) NOT NULL,
  `ProductoFechaEntrada` DATE NOT NULL,
  `ProductoFechaVencimiento` DATE NOT NULL,
  `ProductoCantidadInicial` INT(4) NOT NULL,
  `ProductoPrecioUnitario` DECIMAL(14,2) NOT NULL,
  `Categoria_Producto_idCategoriaProducto` INT NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TipoExamen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TipoExamen` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TipoExamen` (
  `idTipoExamen` INT NOT NULL AUTO_INCREMENT,
  `TipoExamenNombre` VARCHAR(50) NOT NULL,
  `TipoExamenDescripcion` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idTipoExamen`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `NombreUsuario` VARCHAR(45) NOT NULL,
  `PassUsuario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
