/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexion.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jean Martell
 */
public class I_Factura extends javax.swing.JFrame {

    /**
     * Creates new form I_Main
     */
    Connection con=Conexion.ConnectDB();//Conecta a la cadena de conexión
    Date dato = null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    public I_Factura() {
        initComponents();
        setLocationRelativeTo(null); 
        obtener_Data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Discharge = new javax.swing.JLabel();
        lblmain = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Admit = new javax.swing.JLabel();
        lblpacientes = new javax.swing.JLabel();
        Admit2 = new javax.swing.JLabel();
        btnshutdown = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        lbluser1 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnNew = new javax.swing.JButton();
        btnNew1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btncategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(239, 245, 245));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(22, 29, 83));

        jPanel7.setBackground(new java.awt.Color(72, 100, 242));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });

        Discharge.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Discharge.setForeground(java.awt.Color.white);
        Discharge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventory.png_48.png"))); // NOI18N
        Discharge.setText("Inventario");
        Discharge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Discharge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DischargeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Discharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(Discharge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblmain.setBackground(new java.awt.Color(153, 153, 153));
        lblmain.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lblmain.setForeground(new java.awt.Color(255, 255, 255));
        lblmain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mini_logo.png"))); // NOI18N
        lblmain.setText("Laboratorio Clínico");
        lblmain.setToolTipText("Logout");
        lblmain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmainMouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(72, 100, 242));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });

        Admit.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit.setForeground(java.awt.Color.white);
        Admit.setText("Room");
        Admit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmitMouseEntered(evt);
            }
        });

        lblpacientes.setBackground(new java.awt.Color(72, 100, 242));
        lblpacientes.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        lblpacientes.setForeground(java.awt.Color.white);
        lblpacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient.png"))); // NOI18N
        lblpacientes.setText("Pacientes");
        lblpacientes.setToolTipText("");
        lblpacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblpacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpacientesMouseExited(evt);
            }
        });

        Admit2.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit2.setForeground(java.awt.Color.white);
        Admit2.setText("Ward");
        Admit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admit, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addComponent(lblpacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(lblpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Admit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnshutdown.setBackground(new java.awt.Color(255, 153, 153));
        btnshutdown.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnshutdown.setForeground(new java.awt.Color(255, 255, 255));
        btnshutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutdown_48.png"))); // NOI18N
        btnshutdown.setText("Cerrar Sistema");
        btnshutdown.setToolTipText("");
        btnshutdown.setAutoscrolls(true);
        btnshutdown.setBorder(null);
        btnshutdown.setContentAreaFilled(false);
        btnshutdown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnshutdown.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnshutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnshutdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnshutdownMouseExited(evt);
            }
        });
        btnshutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshutdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(lblmain, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnshutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmain, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(btnshutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 620));

        lbluser.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        lbluser.setForeground(new java.awt.Color(0, 0, 0));
        lbluser.setText("Caja");
        jPanel3.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 90, 40));

        lbluser1.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbluser1.setForeground(new java.awt.Color(0, 0, 0));
        lbluser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userr.png"))); // NOI18N
        lbluser1.setText("Maria Ardon");
        jPanel3.add(lbluser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 170, 40));

        txtsearch.setFont(new java.awt.Font("Norasi", 0, 18)); // NOI18N
        txtsearch.setBorder(null);
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel3.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 210, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 210, 10));

        btnNew.setBackground(new java.awt.Color(72, 100, 242));
        btnNew.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        btnNew.setForeground(java.awt.Color.white);
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnNew.setText("Nueva Fac");
        btnNew.setToolTipText("");
        btnNew.setBorderPainted(false);
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.setFocusPainted(false);
        btnNew.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNew.setPreferredSize(new java.awt.Dimension(132, 44));
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 150, 32));

        btnNew1.setBackground(new java.awt.Color(72, 100, 242));
        btnNew1.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        btnNew1.setForeground(java.awt.Color.white);
        btnNew1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_32.png"))); // NOI18N
        btnNew1.setToolTipText("");
        btnNew1.setBorderPainted(false);
        btnNew1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew1.setFocusPainted(false);
        btnNew1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNew1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNew1.setIconTextGap(0);
        btnNew1.setPreferredSize(new java.awt.Dimension(132, 44));
        btnNew1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNew1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNew1MouseExited(evt);
            }
        });
        btnNew1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNew1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 70, 32));

        jScrollPane2.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 1, true));

        tbl.setAutoCreateRowSorter(true);
        tbl.setFont(new java.awt.Font("Norasi", 0, 12)); // NOI18N
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbl.setGridColor(java.awt.Color.pink);
        tbl.setRowHeight(25);
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 680, 440));

        btncategoria.setBackground(new java.awt.Color(72, 100, 242));
        btncategoria.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        btncategoria.setForeground(java.awt.Color.white);
        btncategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btncategoria.setText("Tipo Examen");
        btncategoria.setToolTipText("");
        btncategoria.setBorderPainted(false);
        btncategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncategoria.setFocusPainted(false);
        btncategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btncategoria.setPreferredSize(new java.awt.Dimension(132, 44));
        btncategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncategoriaMouseExited(evt);
            }
        });
        btncategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(btncategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 180, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

          public void obtener_Data(){
        String sql="select NumeroFactura as 'codigo'," +
"                PacienteNombres as 'Nombre'," +
"               PacienteApellidos as 'Apellido'," +
"              TipoExamenNombre as 'Examen'," +
"                FacturacionFecha as 'Fecha'," +
"             FacturacionTipoPago as 'Tipo de Pago'," +
"             FacturacionSubTotal as 'SubTotal'," +
"               FacturacionISV as 'ISV'," +
"               FacturacionTotal as 'Total' from facturacion inner join paciente" +
" on Paciente_idPaciente = PacienteIdentidad inner join tipoexamen" +
" ON  TipoExamen_idTipoExamen= idTipoExamen";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
          tbl.setModel(DbUtils.resultSetToTableModel(rs));
          tbl.removeColumn(tbl.getColumnModel().getColumn(0));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}}
          void buscar(){
           String buscar = txtsearch.getText();
            try{
            DefaultTableModel dt = (DefaultTableModel) tbl.getModel();
            dt.setRowCount(0);
            Statement s = Conexion.ConnectDB().createStatement();
            
            ResultSet rs = s.executeQuery("select NumeroFactura as 'codigo'," +
"                PacienteNombres as 'Nombre'," +
"               PacienteApellidos as 'Apellido'," +
"              TipoExamenNombre as 'Examen'," +
"                FacturacionFecha as 'Fecha'," +
"             FacturacionTipoPago as 'Tipo de Pago'," +
"             FacturacionSubTotal as 'SubTotal'," +
"               FacturacionISV as 'ISV'," +
"               FacturacionTotal as 'Total' from facturacion inner join paciente" +
" on Paciente_idPaciente = PacienteIdentidad inner join tipoexamen" +
" ON  TipoExamen_idTipoExamen= idTipoExamen  where PacienteNombres like '%"+buscar+"%'");
            while (rs.next()){
                Vector v = new Vector();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                dt.addRow(v);
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                obtener_Data();
            } 
          }
    private void DischargeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DischargeMouseClicked


    }//GEN-LAST:event_DischargeMouseClicked

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited

    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered

    }//GEN-LAST:event_jPanel7MouseEntered

    private void lblmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmainMouseClicked
        this.dispose();
        I_Main f = new I_Main();
        f.setVisible(true);
    }//GEN-LAST:event_lblmainMouseClicked

    private void AdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseClicked

    }//GEN-LAST:event_AdmitMouseClicked

    private void AdmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseExited
        jPanel10.setBackground(new Color(52,70,93));  // TODO add your handling code here:
    }//GEN-LAST:event_AdmitMouseExited

    private void AdmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseEntered

    }//GEN-LAST:event_AdmitMouseEntered

    private void lblpacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpacientesMouseClicked
        this.dispose();
        I_Pacientes f = new I_Pacientes();
        f.show();
    }//GEN-LAST:event_lblpacientesMouseClicked

    private void lblpacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpacientesMouseEntered

    }//GEN-LAST:event_lblpacientesMouseEntered

    private void lblpacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpacientesMouseExited

    }//GEN-LAST:event_lblpacientesMouseExited

    private void Admit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseClicked

    }//GEN-LAST:event_Admit2MouseClicked

    private void Admit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseExited

    private void Admit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(new Color(52,70,93));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered

    }//GEN-LAST:event_jPanel10MouseEntered

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited

    }//GEN-LAST:event_btnNewMouseExited

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered

    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        new I_New_Fact(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnNew1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNew1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNew1MouseExited

    private void btnNew1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNew1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNew1MouseEntered

    private void btnNew1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNew1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNew1ActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblMouseClicked

    private void btncategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncategoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btncategoriaMouseEntered

    private void btncategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncategoriaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btncategoriaMouseExited

    private void btncategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoriaActionPerformed
        new I_Tipo_Examen(new JFrame(), true).setVisible(true);              // TODO add your handling code here:
    }//GEN-LAST:event_btncategoriaActionPerformed

    private void btnshutdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshutdownMouseEntered
        btnshutdown.setBackground(new Color(72, 100, 242));        // TODO add your handling code here:
    }//GEN-LAST:event_btnshutdownMouseEntered

    private void btnshutdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnshutdownMouseExited
        btnshutdown.setBackground(new Color(58, 76, 214));// TODO add your handling code here:
    }//GEN-LAST:event_btnshutdownMouseExited

    private void btnshutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshutdownActionPerformed
        int P = JOptionPane.showConfirmDialog(null," Seguro que desea Cerrar el Sistema ?","Confirmación",JOptionPane.YES_NO_OPTION);
        if (P==0){
            System.exit(0);
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnshutdownActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        buscar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admit;
    private javax.swing.JLabel Admit2;
    private javax.swing.JLabel Discharge;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNew1;
    private javax.swing.JButton btncategoria;
    private javax.swing.JButton btnshutdown;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblmain;
    private javax.swing.JLabel lblpacientes;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbluser1;
    protected static javax.swing.JTable tbl;
    public javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
