/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;

/**
 *
 * @author Jean Martell
 */
public class I_Main extends javax.swing.JFrame {

    /**
     * Creates new form I_Main
     */
    public I_Main() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Room = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Admit3 = new javax.swing.JLabel();
        Admit4 = new javax.swing.JLabel();
        lblinventario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Admit = new javax.swing.JLabel();
        lblpatient = new javax.swing.JLabel();
        Admit2 = new javax.swing.JLabel();
        pnlfactura = new javax.swing.JPanel();
        btnfactura = new javax.swing.JButton();
        lbluser = new javax.swing.JLabel();
        lbluser1 = new javax.swing.JLabel();
        pnlcontabilidad = new javax.swing.JPanel();
        btnconta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(239, 245, 245));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(22, 29, 83));

        jPanel6.setBackground(new java.awt.Color(72, 100, 242));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        Room.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Room.setForeground(java.awt.Color.white);
        Room.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutdown_48.png"))); // NOI18N
        Room.setText("Cerrar Sistema");
        Room.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RoomMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RoomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RoomMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Room, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Room, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBackground(new java.awt.Color(72, 100, 242));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });

        Admit3.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit3.setForeground(java.awt.Color.white);
        Admit3.setText("Room");
        Admit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit3MouseEntered(evt);
            }
        });

        Admit4.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit4.setForeground(java.awt.Color.white);
        Admit4.setText("Ward");
        Admit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit4MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit4MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit4MouseEntered(evt);
            }
        });

        lblinventario.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        lblinventario.setForeground(java.awt.Color.white);
        lblinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventory.png_48.png"))); // NOI18N
        lblinventario.setText("Inventario");
        lblinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinventarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Admit4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admit3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblinventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Admit4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mini_logo.png"))); // NOI18N
        jLabel1.setText("Laboratorio Clínico");
        jLabel1.setToolTipText("Logout");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(72, 100, 242));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });

        Admit.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit.setForeground(java.awt.Color.white);
        Admit.setText("Room");
        Admit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmitMouseEntered(evt);
            }
        });

        lblpatient.setBackground(new java.awt.Color(72, 100, 242));
        lblpatient.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        lblpatient.setForeground(java.awt.Color.white);
        lblpatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient.png"))); // NOI18N
        lblpatient.setText("Pacientes");
        lblpatient.setToolTipText("");
        lblpatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblpatient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpatientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpatientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpatientMouseExited(evt);
            }
        });

        Admit2.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit2.setForeground(java.awt.Color.white);
        Admit2.setText("Ward");
        Admit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admit, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addComponent(lblpatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(lblpatient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Admit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 620));

        pnlfactura.setBackground(new java.awt.Color(58, 76, 214));
        pnlfactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        pnlfactura.setPreferredSize(new java.awt.Dimension(130, 130));
        pnlfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlfacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlfacturaMouseExited(evt);
            }
        });

        btnfactura.setBackground(new java.awt.Color(58, 76, 214));
        btnfactura.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnfactura.setForeground(new java.awt.Color(255, 255, 255));
        btnfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bill_64.png"))); // NOI18N
        btnfactura.setText("Facturación");
        btnfactura.setToolTipText("");
        btnfactura.setBorder(null);
        btnfactura.setContentAreaFilled(false);
        btnfactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnfactura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnfactura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnfacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnfacturaMouseExited(evt);
            }
        });
        btnfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlfacturaLayout = new javax.swing.GroupLayout(pnlfactura);
        pnlfactura.setLayout(pnlfacturaLayout);
        pnlfacturaLayout.setHorizontalGroup(
            pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnfactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlfacturaLayout.setVerticalGroup(
            pnlfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnfactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(pnlfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 210, 270));

        lbluser.setFont(new java.awt.Font("Raleway", 1, 24)); // NOI18N
        lbluser.setForeground(new java.awt.Color(0, 0, 0));
        lbluser.setText("Bienvenido(a) al Sistema ARFE");
        jPanel3.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 370, 40));

        lbluser1.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbluser1.setForeground(new java.awt.Color(0, 0, 0));
        lbluser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userr.png"))); // NOI18N
        lbluser1.setText("Maria Ardon");
        jPanel3.add(lbluser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 170, 40));

        pnlcontabilidad.setBackground(new java.awt.Color(72, 100, 242));
        pnlcontabilidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        pnlcontabilidad.setPreferredSize(new java.awt.Dimension(130, 130));
        pnlcontabilidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlcontabilidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlcontabilidadMouseExited(evt);
            }
        });

        btnconta.setBackground(new java.awt.Color(204, 204, 255));
        btnconta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnconta.setForeground(new java.awt.Color(255, 255, 255));
        btnconta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accounting_64.png"))); // NOI18N
        btnconta.setText("Contabilidad");
        btnconta.setToolTipText("");
        btnconta.setBorder(null);
        btnconta.setContentAreaFilled(false);
        btnconta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnconta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnconta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncontaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncontaMouseExited(evt);
            }
        });
        btnconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlcontabilidadLayout = new javax.swing.GroupLayout(pnlcontabilidad);
        pnlcontabilidad.setLayout(pnlcontabilidadLayout);
        pnlcontabilidadLayout.setHorizontalGroup(
            pnlcontabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcontabilidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnconta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlcontabilidadLayout.setVerticalGroup(
            pnlcontabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlcontabilidadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnconta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(pnlcontabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 210, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseClicked
        System.exit(0);
    }//GEN-LAST:event_RoomMouseClicked

    private void RoomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseEntered
        jPanel6.setBackground(new Color(30,34,61));        // TODO add your handling code here:
    }//GEN-LAST:event_RoomMouseEntered

    private void RoomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RoomMouseExited
        jPanel6.setBackground(new Color(52,73,94));         // TODO add your handling code here:
    }//GEN-LAST:event_RoomMouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(30,34,61));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(52,73,94));        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseExited

    private void lblinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinventarioMouseClicked
        this.dispose();
        I_Inventario f = new I_Inventario();
        f.show();

    }//GEN-LAST:event_lblinventarioMouseClicked

    private void Admit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit3MouseClicked

    }//GEN-LAST:event_Admit3MouseClicked

    private void Admit3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit3MouseExited

    private void Admit3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit3MouseEntered

    private void Admit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit4MouseClicked

    }//GEN-LAST:event_Admit4MouseClicked

    private void Admit4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit4MouseExited

    private void Admit4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit4MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited

    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered

    }//GEN-LAST:event_jPanel7MouseEntered

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

    }//GEN-LAST:event_jLabel1MouseClicked

    private void AdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseClicked

    }//GEN-LAST:event_AdmitMouseClicked

    private void AdmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseExited
        jPanel10.setBackground(new Color(52,70,93));  // TODO add your handling code here:
    }//GEN-LAST:event_AdmitMouseExited

    private void AdmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseEntered

    }//GEN-LAST:event_AdmitMouseEntered

    private void lblpatientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpatientMouseClicked
       this.dispose();
       I_Pacientes f = new I_Pacientes();
       f.setVisible(true);

    }//GEN-LAST:event_lblpatientMouseClicked

    private void lblpatientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpatientMouseEntered

    }//GEN-LAST:event_lblpatientMouseEntered

    private void lblpatientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpatientMouseExited

    }//GEN-LAST:event_lblpatientMouseExited

    private void Admit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseClicked

    }//GEN-LAST:event_Admit2MouseClicked

    private void Admit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseExited

    private void Admit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(new Color(52,70,93));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered

    }//GEN-LAST:event_jPanel10MouseEntered

    private void pnlfacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlfacturaMouseExited
        //pnlcontabilidad.setBackground(new Color(52,70,93));// TODO add your handling code here:
    }//GEN-LAST:event_pnlfacturaMouseExited

    private void pnlfacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlfacturaMouseEntered
       // pnlcontabilidad.setBackground(new Color(58, 76, 214)); // TODO add your handling code here:
    }//GEN-LAST:event_pnlfacturaMouseEntered

    private void btnfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfacturaActionPerformed
        this.dispose();
        I_Factura f = new I_Factura();
        f.show();// TODO add your handling code here:
    }//GEN-LAST:event_btnfacturaActionPerformed

    private void btnfacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaMouseExited
        pnlfactura.setBackground(new Color(58, 76, 214));// TODO add your handling code here:
    }//GEN-LAST:event_btnfacturaMouseExited

    private void btnfacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfacturaMouseEntered
        pnlfactura.setBackground(new Color(72, 100, 242));        // TODO add your handling code here:
    }//GEN-LAST:event_btnfacturaMouseEntered

    private void btncontaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncontaMouseEntered
        pnlcontabilidad.setBackground(new Color(58, 76, 214));  // TODO add your handling code here:
    }//GEN-LAST:event_btncontaMouseEntered

    private void btncontaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncontaMouseExited
        pnlcontabilidad.setBackground(new Color(72, 100, 242));;   
        // TODO add your handling code here:
    }//GEN-LAST:event_btncontaMouseExited

    private void btncontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncontaActionPerformed

    private void pnlcontabilidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcontabilidadMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlcontabilidadMouseEntered

    private void pnlcontabilidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcontabilidadMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlcontabilidadMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admit;
    private javax.swing.JLabel Admit2;
    private javax.swing.JLabel Admit3;
    private javax.swing.JLabel Admit4;
    private javax.swing.JLabel Room;
    private javax.swing.JButton btnconta;
    private javax.swing.JButton btnfactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblinventario;
    private javax.swing.JLabel lblpatient;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbluser1;
    private javax.swing.JPanel pnlcontabilidad;
    private javax.swing.JPanel pnlfactura;
    // End of variables declaration//GEN-END:variables
}
