/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexion.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Jean Martell
 */
public class I_Pacientes extends javax.swing.JFrame {

    /**
     * Creates new form I_Main
     */
    Connection con=Conexion.ConnectDB();//Conecta a la cadena de conexión
Date dato = null;
ResultSet rs=null;
PreparedStatement pst=null;

    public I_Pacientes() {
        initComponents();
        setLocationRelativeTo(null);
        Get_Data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblshutdown = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblinventario = new javax.swing.JLabel();
        lblmain = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Admit = new javax.swing.JLabel();
        lblpacientes = new javax.swing.JLabel();
        Admit2 = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lbluser1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpacientes = new javax.swing.JTable();
        txtDoctorName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnNew = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(239, 245, 245));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(10, 24, 39), 1, true));
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(22, 29, 83));

        jPanel6.setBackground(new java.awt.Color(72, 100, 242));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        lblshutdown.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        lblshutdown.setForeground(java.awt.Color.white);
        lblshutdown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/shutdown_48.png"))); // NOI18N
        lblshutdown.setText("Cerrar Sistema");
        lblshutdown.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblshutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblshutdownMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblshutdownMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblshutdownMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblshutdown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblshutdown, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBackground(new java.awt.Color(72, 100, 242));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
        });

        lblinventario.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        lblinventario.setForeground(java.awt.Color.white);
        lblinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/inventory.png_48.png"))); // NOI18N
        lblinventario.setText("Inventario");
        lblinventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblinventarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblinventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblmain.setBackground(new java.awt.Color(153, 153, 153));
        lblmain.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        lblmain.setForeground(new java.awt.Color(255, 255, 255));
        lblmain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mini_logo.png"))); // NOI18N
        lblmain.setText("Laboratorio Clínico");
        lblmain.setToolTipText("Logout");
        lblmain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblmain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblmainMouseClicked(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(72, 100, 242));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
        });

        Admit.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit.setForeground(java.awt.Color.white);
        Admit.setText("Room");
        Admit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdmitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdmitMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdmitMouseEntered(evt);
            }
        });

        lblpacientes.setBackground(new java.awt.Color(72, 100, 242));
        lblpacientes.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        lblpacientes.setForeground(java.awt.Color.white);
        lblpacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/patient.png"))); // NOI18N
        lblpacientes.setText("Pacientes");
        lblpacientes.setToolTipText("");
        lblpacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblpacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblpacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblpacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblpacientesMouseExited(evt);
            }
        });

        Admit2.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        Admit2.setForeground(java.awt.Color.white);
        Admit2.setText("Ward");
        Admit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Admit2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Admit2MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Admit2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Admit, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                .addGap(59, 59, 59))
            .addComponent(lblpacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(lblpacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Admit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Admit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(lblmain, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmain, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 620));

        lbluser.setFont(new java.awt.Font("Raleway", 1, 36)); // NOI18N
        lbluser.setForeground(new java.awt.Color(0, 0, 0));
        lbluser.setText("Lista de Pacientes");
        jPanel3.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 320, 40));

        lbluser1.setFont(new java.awt.Font("Raleway", 1, 18)); // NOI18N
        lbluser1.setForeground(new java.awt.Color(0, 0, 0));
        lbluser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/userr.png"))); // NOI18N
        lbluser1.setText("Maria Ardon");
        jPanel3.add(lbluser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 170, 40));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.white, 1, true));

        tblpacientes.setAutoCreateRowSorter(true);
        tblpacientes.setFont(new java.awt.Font("Norasi", 0, 18)); // NOI18N
        tblpacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblpacientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblpacientes.setGridColor(java.awt.Color.pink);
        tblpacientes.setRowHeight(25);
        tblpacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpacientes);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 680, 440));

        txtDoctorName.setFont(new java.awt.Font("Norasi", 0, 18)); // NOI18N
        txtDoctorName.setBorder(null);
        jPanel3.add(txtDoctorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 114, 210, 30));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 152, 210, 10));

        btnNew.setBackground(new java.awt.Color(72, 100, 242));
        btnNew.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        btnNew.setForeground(java.awt.Color.white);
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/edit.png"))); // NOI18N
        btnNew.setText("Nuevo");
        btnNew.setToolTipText("");
        btnNew.setBorderPainted(false);
        btnNew.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNew.setFocusPainted(false);
        btnNew.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNew.setPreferredSize(new java.awt.Dimension(132, 44));
        btnNew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNewMouseExited(evt);
            }
        });
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel3.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 113, 123, 32));

        btnbuscar.setBackground(new java.awt.Color(72, 100, 242));
        btnbuscar.setFont(new java.awt.Font("Raleway Black", 0, 18)); // NOI18N
        btnbuscar.setForeground(java.awt.Color.white);
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search_32.png"))); // NOI18N
        btnbuscar.setToolTipText("");
        btnbuscar.setBorderPainted(false);
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.setFocusPainted(false);
        btnbuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnbuscar.setIconTextGap(0);
        btnbuscar.setPreferredSize(new java.awt.Dimension(132, 44));
        btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbuscarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbuscarMouseEntered(evt);
            }
        });
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 113, 70, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 928, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //obteder datos de la DB
    private void Get_Data(){
        String sql="select PacienteIdentidad as 'Identidad', PacienteNombres as 'Nombre', PacienteApellidos as 'Apellido', PacienteEdad as 'Edad', PacienteSexo as 'Genero', PacienteTelefono as 'Teléfono',PacienteCorreo as 'Correo', PacienteFecha AS 'Fecha y Hora Ingreso' from paciente";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         tblpacientes.setModel(DbUtils.resultSetToTableModel(rs));
        //tblpacientes.removeColumn(tblpacientes.getColumnModel().getColumn(0));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
  }
    private void lblshutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshutdownMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblshutdownMouseClicked

    private void lblshutdownMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshutdownMouseEntered
        jPanel6.setBackground(new Color(30,34,61));        // TODO add your handling code here:
    }//GEN-LAST:event_lblshutdownMouseEntered

    private void lblshutdownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblshutdownMouseExited
        jPanel6.setBackground(new Color(52,73,94));         // TODO add your handling code here:
    }//GEN-LAST:event_lblshutdownMouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(30,34,61));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(52,73,94));        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseExited

    private void lblinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblinventarioMouseClicked
        this.dispose();
        I_Inventario f= new I_Inventario();
        f.show();

    }//GEN-LAST:event_lblinventarioMouseClicked

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited

    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered

    }//GEN-LAST:event_jPanel7MouseEntered

    private void lblmainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblmainMouseClicked
        this.dispose();
        I_Main f = new I_Main();
        f.setVisible(true);
    }//GEN-LAST:event_lblmainMouseClicked

    private void AdmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseClicked

    }//GEN-LAST:event_AdmitMouseClicked

    private void AdmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseExited
        jPanel10.setBackground(new Color(52,70,93));  // TODO add your handling code here:
    }//GEN-LAST:event_AdmitMouseExited

    private void AdmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdmitMouseEntered

    }//GEN-LAST:event_AdmitMouseEntered

    private void lblpacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpacientesMouseClicked

    }//GEN-LAST:event_lblpacientesMouseClicked

    private void lblpacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpacientesMouseEntered

    }//GEN-LAST:event_lblpacientesMouseEntered

    private void lblpacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblpacientesMouseExited

    }//GEN-LAST:event_lblpacientesMouseExited

    private void Admit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseClicked

    }//GEN-LAST:event_Admit2MouseClicked

    private void Admit2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseExited

    private void Admit2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Admit2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Admit2MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(new Color(52,70,93));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered

    }//GEN-LAST:event_jPanel10MouseEntered

    private void tblpacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpacientesMouseClicked
        try {
            int row= tblpacientes.getSelectedRow();
            // identidad, nombre, apellido, edad, sexo, telefono, correo;
            
            I_New_Paciente.identidad= tblpacientes.getModel().getValueAt(row,0).toString();
            I_New_Paciente.nombre = tblpacientes.getModel().getValueAt(row,1).toString();
            I_New_Paciente.apellido = tblpacientes.getModel().getValueAt(row,2).toString();
            I_New_Paciente.edad = tblpacientes.getModel().getValueAt(row,3).toString();
            I_New_Paciente.sexo = tblpacientes.getModel().getValueAt(row,4).toString();
            I_New_Paciente.telefono = tblpacientes.getModel().getValueAt(row,5).toString();
            I_New_Paciente.correo = tblpacientes.getModel().getValueAt(row,6).toString();
          
            new I_New_Paciente(new JFrame(), true).setVisible(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }      
    }//GEN-LAST:event_tblpacientesMouseClicked

    private void btnNewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseExited

    }//GEN-LAST:event_btnNewMouseExited

    private void btnNewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewMouseEntered

    }//GEN-LAST:event_btnNewMouseEntered

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        new I_New_Paciente(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnbuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarMouseExited

    private void btnbuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarMouseEntered

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(I_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(I_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(I_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(I_Pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new I_Pacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admit;
    private javax.swing.JLabel Admit2;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblinventario;
    private javax.swing.JLabel lblmain;
    private javax.swing.JLabel lblpacientes;
    private javax.swing.JLabel lblshutdown;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lbluser1;
    private javax.swing.JTable tblpacientes;
    public javax.swing.JTextField txtDoctorName;
    // End of variables declaration//GEN-END:variables
}
